---
# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: Apache-2.0
- name: Apply sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/90-flow-ingest.conf
  changed_when: true
  tags:
    - opennms_tarball_prereqs
