---
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/azure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/kvm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/proxmox"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
