---
# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: Apache-2.0
- name: Restart clickhouse
  ansible.builtin.service:
    name: clickhouse-server.service
    state: restarted
  tags:
    - clickhouse
    - systemd
