{
 "title": "Prometheus: OpenNMS Core Internals",
 "description": "Monitoring of internal JMX metrics from the OpenNMS Core system collected via JMX exporter for Prometheus.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheusDS", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"jmx_core\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OpenNMS Collect Daemon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool",
     "type": "timeseries",
     "description": "Collectd thread usage statistics ",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_collectd_activethreads{instance=\"$instance\"}",
       "legendFormat": "active"
      },
      {
       "expr": "opennms_collectd_maxpoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Scheduler",
     "type": "timeseries",
     "description": "Collectd scheduler task statistics",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_collectd_taskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "opennms_collectd_taskcompletionratio",
       "legendFormat": "ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenNMS Provisioning Daemon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import Thread Pool",
     "type": "timeseries",
     "description": "Provisiond import thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_importactivethreads{instance=\"$instance\"}",
       "legendFormat": "import active"
      },
      {
       "expr": "opennms_provisiond_importcorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Writer Thread Pool",
     "type": "timeseries",
     "description": "Provisiond writer thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_writeactivethreads{instance=\"$instance\"}",
       "legendFormat": "writer active"
      },
      {
       "expr": "opennms_provisiond_writecorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Scan Thread Pool",
     "type": "timeseries",
     "description": "Provisiond scan thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_scanactivethreads{instance=\"$instance\"}",
       "legendFormat": "scan active"
      },
      {
       "expr": "opennms_provisiond_scancorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Scheduler Thread Pool",
     "type": "timeseries",
     "description": "Provisiond scheduler thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_scheduledactivethreads{instance=\"$instance\"}",
       "legendFormat": "scheduler active"
      },
      {
       "expr": "opennms_provisiond_scheduledcorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Import Scheduler",
     "type": "timeseries",
     "description": "Provisiond import scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_importtaskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_importtaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_importtaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Writer Scheduler",
     "type": "timeseries",
     "description": "Provisiond writer scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_writetaskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_writetaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_writetaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Scan Scheduler",
     "type": "timeseries",
     "description": "Provisiond scan scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_scantaskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_scantaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_scantaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Scheduler",
     "type": "timeseries",
     "description": "Provisiond scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(opennms_provisiond_scheduledtaskqueuependingcount{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_scheduledtaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_scheduledtaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenNMS Trapd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Trap Reception",
     "type": "timeseries",
     "description": "Statistics about received SNMP Traps and their versions processed by the OpenNMS Core system.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(opennms_trapd_v1trapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "v1"
      },
      {
       "expr": "rate(opennms_trapd_v2ctrapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "v2c"
      },
      {
       "expr": "rate(opennms_trapd_v3trapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "v3"
      },
      {
       "expr": "rate(opennms_trapd_vunknowntrapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "unknown"
      }
     ]
    },
    {
     "title": "SNMP Trap Failures",
     "type": "timeseries",
     "description": "Statistics about SNMP trap reception failures. ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(opennms_trapd_trapsdiscarded{instance=~\"$instance\"}[1m])",
       "legendFormat": "discarded"
      },
      {
       "expr": "rate(opennms_trapd_trapserrored{instance=~\"$instance\"}[1m])",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "SNMP Trap IPC Consumer Dispatch",
     "type": "timeseries",
     "description": "Statistics about IPC consumer dispatch time for SNMP Traps internally",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    },
    {
     "title": "SNMP Trap IPC Producer Dispatch",
     "type": "timeseries",
     "description": "Statistics about IPC producer dispatch time for SNMP Traps internally",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenNMS Syslogd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog conversation ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_syslogd_consumer_toevent_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "syslog to event"
      }
     ]
    }
   ]
  },
  {
   "title": "Java Virtual Machine - Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Throughput",
     "type": "stat",
     "description": "These calculations are experimental and need yet to be compared and validated against known correct results.",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "Garbage Collection Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 2, "y": 93 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "Garbage Collection Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Throughput Evolution",
     "type": "timeseries",
     "description": "These calculations are experimental and need yet to be compared and validated against known correct results.  The way it is built does not work for multiple simultaneous JVMs, so accuracy requires selecting only one.",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "GC Time (period)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[$__range]))",
       "legendFormat": "{{job}}-{{gc}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Java Virtual Machine - Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_current{instance=~\"$instance\"}",
       "legendFormat": "{{app}} {{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
       "legendFormat": "{{app}} {{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "Thread State",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 94 },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$instance\"}",
       "legendFormat": "{{state}} - {{app}} {{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "Runnable Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$instance\",state=\"RUNNABLE\"}",
       "legendFormat": "{{app}} {{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "Waiting Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$instance\",state=~\"WAITING\"}",
       "legendFormat": "{{app}} {{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "New Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$instance\",state=\"NEW\"}",
       "legendFormat": "{{app}} {{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "Blocked Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$instance\",state=\"BLOCKED\"}",
       "legendFormat": "{{app}} {{pod}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Java Virtual Machine - Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "jvm_classes_loaded_total{instance=~\"$instance\"}",
       "legendFormat": "Loaded - {{app}} {{pod}} {{instance}}"
      },
      {
       "expr": "jvm_classes_unloaded_total{instance=~\"$instance\"}",
       "legendFormat": "Unloaded - {{app}} {{pod}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}