{
 "title": "Prometheus: Java Virtual Machine",
 "description": "Monitoring of internal JMX metrics from the Java Virtual Machine via JMX exporter for Prometheus.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheusDS", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"jmx\", app=\"core\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Java Virtual Machine - Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\"}",
     "legendFormat": "{{state}} - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Runnable Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\",state=\"RUNNABLE\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\",state=\"BLOCKED\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "New Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\",state=\"NEW\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Waiting Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\",state=~\"WAITING\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  { "title": "Java Virtual Machine - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GC Throughput",
   "type": "stat",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Garbage Collection Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 2, "y": 11 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Throughput Evolution",
   "type": "timeseries",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.  The way it is built does not work for multiple simultaneous JVMs, so accuracy requires selecting only one.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "GC Time (period)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{job}}-{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "{{job}}-{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\"})",
     "legendFormat": "{{job}}-{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "{{job}}-{{gc}} {{pod}}"
    }
   ]
  },
  { "title": "Java Virtual Machine - Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{instance=~\"$instance\"}",
     "legendFormat": "Loaded - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_classes_unloaded_total{instance=~\"$instance\"}",
     "legendFormat": "Unloaded - {{app}} {{pod}} {{instance}}"
    }
   ]
  }
 ]
}