{
 "title": "IP Mediation (ONMS) Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "label_variable",
    "query": "app_kubernetes_io_name=\"onms-core\""
   }
  ]
 },
 "panels": [
  { "title": "Overall System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Node Count", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 }, "options": { "content": "# Comes from ONMS level data" } },
  { "title": "Swap Usage", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 }, "options": { "content": "# Comes from OS level data" } },
  {
   "title": "JVM Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{$label_variable})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{$label_variable})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Collectd Thread Pool",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_collectd_activethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_collectd_maxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Pollerd Thread Pool",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_pollerd_activethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_pollerd_maxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Provisiond Importer Thread Pool",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_provisiond_importactivethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_provisiond_importmaxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage: Heap",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{$label_variable,area=\"heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_max_bytes{$label_variable,area=\"heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Collectd Queued Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_collectd_taskqueuependingcount{$label_variable}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pollerd Queued Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_pollerd_taskqueuependingcount{$label_variable}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisiond Scan Thread Pool",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_provisiond_scanactivethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_provisiond_scanmaxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Alarm Count", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 }, "options": { "content": "# Comes from ONMS level data" } },
  { "title": "CPU Usage", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 }, "options": { "content": "# Comes from OS level data" } },
  {
   "title": "JVM Open File Descriptors",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{$label_variable}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{$label_variable}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Provisiond Writer Thread Pool",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_provisiond_writeactivethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_provisiond_writemaxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Event Count", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 }, "options": { "content": "# Comes from ONMS level data" } },
  {
   "title": "Provisiond Scheduler Thread Pool",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_provisiond_scheduledactivethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_provisiond_scheduledmaxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "JVM Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{$label_variable})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{$label_variable})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage: Heap",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{$label_variable,area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{$label_variable,area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{$label_variable}",
     "legendFormat": "Used"
    },
    {
     "expr": "process_max_fds{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{$label_variable}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time Overhead Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{$label_variable}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Average GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{$label_variable}[5m]) / rate(jvm_gc_collection_seconds_count{$label_variable}[5m]) ",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "PostgreSQL Database Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PostgreSQL Graphs",
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 33 },
   "options": {
    "content": "# These will come from PostgreSQL Data"
   }
  },
  { "title": "Collectd Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Collectd Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "opennms_collectd_activethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_collectd_maxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Collectd Tasks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 40 },
   "targets": [
    {
     "expr": "opennms_collectd_taskqueuependingcount{$label_variable}",
     "legendFormat": "Pending Tasks"
    },
    {
     "expr": "opennms_collectd_taskcompletionratio{$label_variable}",
     "legendFormat": "Completion Ratio"
    }
   ]
  },
  { "title": "Pollerd Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pollerd Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "opennms_pollerd_activethreads{$label_variable}",
     "legendFormat": "Active"
    },
    {
     "expr": "opennms_pollerd_maxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Pollerd Tasks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 52 },
   "targets": [
    {
     "expr": "opennms_pollerd_taskqueuependingcount{$label_variable}",
     "legendFormat": "Pending Tasks"
    },
    {
     "expr": "opennms_pollerd_taskcompletionratio{$label_variable}",
     "legendFormat": "Completion Ratio"
    }
   ]
  },
  { "title": "Provisiond Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Provisiond Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "opennms_provisiond_importactivethreads{$label_variable}",
     "legendFormat": "Active (Import)"
    },
    {
     "expr": "opennms_provisiond_scanactivethreads{$label_variable}",
     "legendFormat": "Active (Scan)"
    },
    {
     "expr": "opennms_provisiond_writeactivethreads{$label_variable}",
     "legendFormat": "Active (Write)"
    },
    {
     "expr": "opennms_provisiond_scheduledactivethreads{$label_variable}",
     "legendFormat": "Active (Scheduled)"
    },
    {
     "expr": "opennms_provisiond_scheduledmaxpoolthreads{$label_variable}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Provisiond (Import) Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 64 },
   "targets": [
    {
     "expr": "opennms_provisiond_importtaskstotal{$label_variable}",
     "legendFormat": "Total"
    },
    {
     "expr": "opennms_provisiond_importtaskqueuependingcount{$label_variable}",
     "legendFormat": "Pending"
    },
    {
     "expr": "opennms_provisiond_importtaskscompleted{$label_variable}",
     "legendFormat": "Completed"
    },
    {
     "expr": "opennms_provisiond_importtaskcompletionratio{$label_variable}",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Provisiond (Write) Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 64 },
   "targets": [
    {
     "expr": "opennms_provisiond_writetaskstotal{$label_variable}",
     "legendFormat": "Total"
    },
    {
     "expr": "opennms_provisiond_writetaskqueuependingcount{$label_variable}",
     "legendFormat": "Pending"
    },
    {
     "expr": "opennms_provisiond_writetaskscompleted{$label_variable}",
     "legendFormat": "Completed"
    },
    {
     "expr": "opennms_provisiond_writetaskcompletionratio{$label_variable}",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Provisiond (Scan) Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 71 },
   "targets": [
    {
     "expr": "opennms_provisiond_scantaskstotal{$label_variable}",
     "legendFormat": "Total"
    },
    {
     "expr": "opennms_provisiond_scantaskqueuependingcount{$label_variable}",
     "legendFormat": "Pending"
    },
    {
     "expr": "opennms_provisiond_scantaskscompleted{$label_variable}",
     "legendFormat": "Completed"
    },
    {
     "expr": "opennms_provisiond_scantaskcompletionratio{$label_variable}",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Provisiond (Schedule) Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 71 },
   "targets": [
    {
     "expr": "opennms_provisiond_scheduledtaskstotal{$label_variable}",
     "legendFormat": "Total"
    },
    {
     "expr": "opennms_provisiond_scheduledtaskqueuependingcount{$label_variable}",
     "legendFormat": "Pending"
    },
    {
     "expr": "opennms_provisiond_scheduledtaskscompleted{$label_variable}",
     "legendFormat": "Completed"
    },
    {
     "expr": "opennms_provisiond_scheduledtaskcompletionratio{$label_variable}",
     "legendFormat": "Ratio"
    }
   ]
  }
 ]
}